### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [fibo/play.tris3d.net#1]
If I read your code right: https://github.com/fibo/play.tris3d.net/blob/master/src/db.js

You are in fact executing all of the 9 requests while loading the module. This is definitely not something you'd want to do ;)

**Comment by fibo** [comment]
Thank you for your hint.

It should not execute a query, for example

```
const one = (statement) => query.one.bind(query, statement)
```
should correspond in ES5 to

```
function one (statement) {
  return query.one.bind(query, statement)
}
```

and it should return a binded function. If they were executed they would raise an error I guess, since they require a parameter.

By the way, thank you very much for pg-promise: I found it a really good piece of software!

**Comment by fibo** [comment]
I added a more explicit code. Also, if I run `DEBUG=tris3d:* node test/db.js` I see this output which shows that only the selected query runs

<img width="517" alt="screen shot 2016-03-07 at 12 12 39" src="https://cloud.githubusercontent.com/assets/176730/13567908/57816286-e45e-11e5-926e-e683a890be79.png">

**Comment by vitaly-t** [comment]
Ok, I must have misread it then.

**Comment by fibo** [comment]
@vitaly-t thanks btw, every feedback is welcome
